### ISSUE TITLE
Where i can buy DFL168A IC?

### ISSUE THREAD

**Issue by arminsalcin** [Dafulai/DFL168A-Sync-Library#2]
As the title says , where i can buy this ic and what is price ?

**Comment by Dafulai** [comment]
Please directly purchase on http://dafulaielectronics.com/order.html 
Pay by Paypal or Credit card or Bank Transfer.
For Bank transfer, please directly contact email address: sales@dafulaielectronics.com
Usually, it will ship within 2 business days after payment confirmation.
This parts location is Canada.
